services:
  - type: service
    name: text2sign
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind=0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
